// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sodt_permutation_loop
Rcpp::List sodt_permutation_loop(Rcpp::List G0_list, Rcpp::List G1_list, Rcpp::List HY_list);
RcppExport SEXP _CORDE_sodt_permutation_loop(SEXP G0_listSEXP, SEXP G1_listSEXP, SEXP HY_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type G0_list(G0_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type G1_list(G1_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type HY_list(HY_listSEXP);
    rcpp_result_gen = Rcpp::wrap(sodt_permutation_loop(G0_list, G1_list, HY_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CORDE_sodt_permutation_loop", (DL_FUNC) &_CORDE_sodt_permutation_loop, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CORDE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
