# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sodt_permutation_loop <- function(G0_list, G1_list, HY_list) {
    .Call(`_CORDE_sodt_permutation_loop`, G0_list, G1_list, HY_list)
}

